# -*- coding: utf-8 -*-
"""Sprint 06 - EP04 - Logistic Regression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Mhf5OKvR-CqV8tXts-waeTO_MO08OF5
"""

## Logistic Regreesion Example
happiness <- c(10, 8, 9, 7, 8, 5, 9, 6, 8, 7, 1, 1, 3, 1, 4, 5, 6, 3, 2, 0)
divorce <- c(0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1)

df <- data.frame(happiness, divorce)

## Fit logistic Regreesion Full data set
model <- glm(divorce ~ happiness, data = df, family = "binomial")

summary(model)

## Predict and Evaluate Model
df$prob_divorce <- predict(model, type = "response")
df$pred_divorce <- ifelse(df$prob_divorce >= 0.5, 1, 0)

## confusion matrix
confusion_maxtric <- table(df$pred_divorce, df$divorce,
      dnn = c("Predicted", "Actual"))

confusion_maxtric

## Model Evaluation
cat("Accuracy:",confusion_maxtric[1,1] + confusion_maxtric[2,2] / sum(confusion_maxtric))
cat("Precision:",confusion_maxtric[2,2] / confusion_maxtric[2,1] + confusion_maxtric[2,2])
cat("Recall:",confusion_maxtric[2,2] / confusion_maxtric[1,2] + confusion_maxtric[2,2])

cat("F1: ", 2 * ((6.67*6.25) / (6.67+6.25)))